Val sf5.4
puzzle-org/amqp pull request #48
Opened 2022-11-22 10:47 UTC by ValentinCoulon

Toujours en wip, créé pour vérifier l'intégration continue

2022-11-29 14:52 UTC, Niktux requested changes

2022-11-29 14:52 UTC, Niktux commented on features/bootstrap/SendContext.php
> +        $queue = $this->client->getQueue($queueName);
Ca me gêne grandement de s'auto utiliser pour s'auto valider
=> ticket dette technique sur ce repo pour retrouver une autre lib qui se connecte via l'api rest (et non en amqp) (ex: https://github.com/avto-dev/rabbitmq-api-client ... je ne sais pas ce qu'elle vaut) et fixer ces tests 
=> ticket **memo** qui pointe vers ce ticket (sinon on va l'oublier)

2022-11-29 14:52 UTC, Niktux commented on src/Commands/Worker/Run.php
> -        $output->writeln("<error>Worker $workerName not found</error>");
Pourquoi ce message a disparu ? 
C'est une commande de prod, on ne peut pas se contenter d'une exception => il faut catcher et informer

2022-11-29 14:52 UTC, Niktux commented on src/Events/WorkerProcess.php
> +class WorkerProcess extends Event
final

2022-11-29 14:52 UTC, Niktux commented on src/Events/WorkerProcessed.php
> +class WorkerProcessed extends Event
final

2022-11-29 14:52 UTC, Niktux commented on src/Messages/Bodies/StreamedBinary.php
> +        $this->metadata = new ChunkedMessageMetadata((string) Uuid::uuid4(), $size, $nbChunks, sha1($content));
Utiliser un vo interne à la lib pour se découpler de Ramsey UUID

Garder string pour l'api publique de notre lib

2022-11-29 14:52 UTC, Niktux commented on src/Messages/Bodies/StreamedFile.php
> +            $this->metadata = new ChunkedMessageMetadata((string) Uuid::uuid4(), $size, $nbChunks, sha1_file($filepath));
idem VO

2022-11-29 14:52 UTC, Niktux commented on src/Messages/Chunks/ChunkedMessageMetadata.php
>          $this->uuid = $uuid;
idem VO

2022-11-29 14:52 UTC, Niktux commented on tests/Services/SupervisorConfigurationGeneratorTest.php
> +use Symfony\Component\Console\Output\OutputInterface;
utile ?

2022-11-29 15:05 UTC, ValentinCoulon commented on composer.json
> +            "Puzzle\\AMQP\\" : "tests"
fix: https://github.com/puzzle-org/amqp/pull/48/commits/645ab44e3d10095edbad73d7fe0209cda171be11

2022-11-29 15:17 UTC, ValentinCoulon commented on src/Commands/Worker/Run.php
> -        $output->writeln("<error>Worker $workerName not found</error>");
Avant, l'interface `WorkerProvider::workerFor(string)` ne renvoyait pas forcément une instance d'objet. Il y avait donc une vérification manuel avec ce message d'erreur.
A présent, on est sûr d'avoir une instance de `Worker` grace au typehinting sur le retour de` workerFor(string),` il n'y a donc plus de raison pour passer par une vérification manuelle. Si il y a un soucis, logiquement, une exception sera levée et apparaîtra dans la console.

Pour être sûr il faudrait demander a l'auteur de cette modif : @Niktux de 2020 :p

2022-11-29 15:28 UTC, ValentinCoulon commented on src/Messages/Chunks/ChunkedMessageMetadata.php
>          $this->uuid = $uuid;
95081f7

2022-11-29 15:28 UTC, ValentinCoulon commented on src/Messages/Bodies/StreamedFile.php
> +            $this->metadata = new ChunkedMessageMetadata((string) Uuid::uuid4(), $size, $nbChunks, sha1_file($filepath));
95081f7

2022-11-29 15:28 UTC, ValentinCoulon commented on src/Messages/Bodies/StreamedBinary.php
> +        $this->metadata = new ChunkedMessageMetadata((string) Uuid::uuid4(), $size, $nbChunks, sha1($content));
95081f7

2022-11-29 15:30 UTC, ValentinCoulon commented on tests/Services/SupervisorConfigurationGeneratorTest.php
> +use Symfony\Component\Console\Output\OutputInterface;
non :) 
6f37a61

2022-11-29 15:41 UTC, ValentinCoulon commented on src/Events/WorkerProcessed.php
> +class WorkerProcessed extends Event
5cf4fc7

2022-11-29 15:41 UTC, ValentinCoulon commented on src/Events/WorkerProcess.php
> +class WorkerProcess extends Event
5cf4fc7

2022-11-29 15:42 UTC, ValentinCoulon commented
ajout de [8c59a47](https://github.com/puzzle-org/amqp/pull/48/commits/8c59a47c436202fb15300590d18ad7ddecd3eaf9) et [929c5c9](https://github.com/puzzle-org/amqp/pull/48/commits/929c5c948e978aa7ab1089894b73a7249bd130b9) pour avoir une cohérence sur les Events :)

2022-11-29 15:55 UTC, Niktux commented on src/Commands/Worker/Run.php
> -        $output->writeln("<error>Worker $workerName not found</error>");
Il faudrait catcher ladite exception pour mettre un message user friendly

Tu pourras dire à l'auteur de cette modif que c'est un noob

2022-11-29 15:58 UTC, Niktux approved these changes

2022-11-29 16:15 UTC, ValentinCoulon commented on src/Commands/Worker/Run.php
> -        $output->writeln("<error>Worker $workerName not found</error>");
Comme vu ensemble, `WorkerProvider` est une interface, il n'y a donc pas d'exception précise à catcher.
=> Du coup, on catch \Exception
59e948d

2022-12-01 14:04 UTC, ValentinCoulon commented on composer.json
> +        "puzzle/pieces" : "dev-clb-sf5",
fix [0026b60](https://github.com/puzzle-org/amqp/pull/48/commits/0026b6083d9e18be1e7ce93d9b857d9e92a07ee5)

2022-12-01 15:23 UTC, lebris commented on features/bootstrap/SendContext.php
> +        $queue = $this->client->getQueue($queueName);
On tag une pré-release, la release officielle ne sera taggée sur lorsqu'on aura traité cette dette technique et validé les tests

2022-12-01 15:31 UTC, merged

2022-12-01 15:33 UTC, lebris commented
Tagged 5.0.0-beta